driver:
  name: dokken
  privileged: true
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[nexus:default]
    verifier:
      inspec_tests:
        - test/integration/default
    driver:
      ports:
        - '8081:8081' # docker -p

